#!/usr/bin/env bash
set -e

source script/functions

# Start clean.
script/00_build_start.sh

say Create fixtures data container.
docker create \
  --name fixtures-test \
  jumanjiman/fixtures \
  /bin/true || :

say Start dns server so we can refer to test containers by name.
#
# Note: You must bind the DNS port to the management IP to avoid client error:
# ;; reply from unexpected source: yyy.yyy.yyy.yyy#53, expected xxx.xxx.xxx.xxx#53
#
mgmt_ip=$(ip route get 8.8.8.8 | awk '/src/ {print $NF}')
docker run -d \
  --name named-test \
  -p ${mgmt_ip}:53:2253 -p ${mgmt_ip}:53:2253/udp \
  -e public_ipaddress=${mgmt_ip} \
  jumanjiman/named

sleep 5
docker logs named-test

say Start the test containers.
#
# For each container, use the DNS server we started above for name resolution.
#
docker run -d \
  --name db-test \
  -p 8080:8080 -p 8081:8081 \
  --dns=${mgmt_ip} \
  --hostname=puppetdb.inf.ise.com \
  jumanjiman/puppetdb

docker run -d \
  --name master-test \
  -p 8140:8140 \
  --dns=${mgmt_ip} \
  --hostname=puppet.inf.ise.com \
  --volumes-from fixtures-test \
  jumanjiman/puppetmaster

docker run -d \
  --name board-test \
  -p 80:80 \
  --dns=${mgmt_ip} \
  --hostname=puppetboard.inf.ise.com \
  jumanjiman/puppetboard

say Sleep 2 minutes for puppetdb to become ready.
#
for x in $(seq 1 60); do echo -n "."; sleep 1; done
echo
for x in $(seq 1 60); do echo -n "."; sleep 1; done
echo

say Show puppetdb logs
docker logs db-test

say Run puppet agent against master.
#
# Do not use `-i' or else docker waits on stdin and
# does not exit until you press a key.
#
hostname=foo.example.com
cmd='puppet agent -t --server=puppet.inf.ise.com --waitforcert=120'
out=/tmp/docker.out
rm -fr $out
#
docker run --rm -t --dns=${mgmt_ip} --hostname=$hostname jumanjiman/puppetagent $cmd | tee -a $out

say Look for specific messages
grep 'foo is bar' $out
grep 'bar is baz' $out
grep 'baz is foo' $out
grep 'Notice: Finished catalog run' $out || /bin/false

say Query puppetboard for the node.
#
cmd="elinks -dump http://puppetboard.inf.ise.com/node/$hostname"
docker run --rm -t --dns=${mgmt_ip} --hostname=$hostname jumanjiman/puppetagent $cmd | tee -a $out

say Did we find the host in puppetboard?
#
# Fail if we don't find our fqdn in the output.
#
grep "http://puppetboard.inf.ise.com/fact/fqdn/$hostname" $out && echo 'yes'
grep "Internal Server Error" $out && /bin/false

say Clean puppet cert for foo.example.com
#
url="https://${mgmt_ip}:8140/production/certificate_status/${hostname}"
curl -k -X PUT -H "Content-Type: text/pson" --data '{"desired_state":"revoked"}' ${url}
curl -k -X DELETE -H "Accept: pson" ${url}
echo

say Check that "docker logs master-test" is meaningful.
docker logs master-test 2>&1 | tee /tmp/master.log

say Look for specific messages
grep "Signed certificate request for ${hostname}" /tmp/master.log
grep "Compiled catalog for ${hostname} in environment production" /tmp/master.log
grep "Removing file Puppet::SSL::Certificate ${hostname}" /tmp/master.log
