#!/bin/bash
set -e
set -u
set -o noclobber

rm -f ci/vars || :
cat > ci/vars <<EOF
export BUILD_DATE=$(date +%Y%m%dT%H%M)
export VCS_REF=$(git rev-parse --short HEAD)
export TAG=\${BUILD_DATE}-git-\${VCS_REF}
EOF
. ci/vars

source script/functions

rm -f /tmp/start
date > /tmp/start

say Run build scripts in order.
for file in script\/[0-9][0-9]_build_*.sh; do
  $file
done

rm -f /tmp/stop
date > /tmp/stop
