#!/bin/bash
# vim: set sw=2 ts=2 ai et:
set -e
set -u

. ci/vars
tags="
${TAG}
latest
"

# The names of the images as built.
build_names="
jumanjiman/autostager
jumanjiman/puppetboard
jumanjiman/puppetdb
jumanjiman/puppetmaster
"

smitty() {
  echo "[INFO] $@"
  eval $@
}

docker login -u $ROBOT_USER -p $ROBOT_PASS

for build_name in $build_names; do
  echo "===== ${build_name} ====="
  for tag in $tags; do
    tagged_name="${build_name}:${tag}"

    # Ensure the image-to-be-tagged exists.
    docker images | grep ${build_name}

    # Create a new tag.
    smitty docker tag ${build_name} ${tagged_name}

    # Ensure the tagged image exists.
    docker images | grep ${build_name} | grep ${tag}

    # Publish the tagged image.
    smitty docker push ${tagged_name}

    echo
    echo
  done
done

docker logout

curl -X POST 'https://hooks.microbadger.com/images/jumanjiman/autostager/muTosD8RrF9G8IB6BSEeyEj_-aM='
curl -X POST 'https://hooks.microbadger.com/images/jumanjiman/puppetmaster/7zWy4DzQxoPDTcEZIAhJCRSi9_U='
curl -X POST 'https://hooks.microbadger.com/images/jumanjiman/puppetdb/Xb50Cdv5CyZO5-AwenAillWwT_o='
curl -X POST 'https://hooks.microbadger.com/images/jumanjiman/puppetboard/8ZaNNf8dPD-mn7xh8v18TLigYmM='
